version: "3"
services:
  api:
    ports:
      - 8000:8000
    build:
      context: "./"
      dockerfile: Dockerfile.dev
      args:
        PORT: 8000
        NODE_ENV: development
    command: [sh, -c, "knex migrate:rollback && knex migrate:latest && knex seed:run && npm run dev"]
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - PORT=8000
      - NODE_ENV=development
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
