### BASE
FROM node:8-alpine
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . .

### DEPENDENCIES
RUN npm install
RUN npm install knex -g

### RELEASE
ARG PORT
ENV PORT=$PORT
EXPOSE $PORT
ARG NODE_ENV
ENV NODE_ENV=$NODE_ENV
HEALTHCHECK --interval=5s \
            --timeout=5s \
            --retries=6 \
            CMD curl -fs http://localhost:$PORT/ || exit 1
