version: "2"
services:
  api:
    ports:
      - 8001:8001
    build:
      context: "./"
      dockerfile: Dockerfile.dev
      args:
        PORT: 8001
        NODE_ENV: test
    command: npm run test
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - PORT=8001
      - NODE_ENV=test
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
